name: dart_application_1
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  date_format: ^2.0.7
  password_strength: ^0.2.0
  # path: ^1.8.0
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
